# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninfo.proto\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"M\n\x0bInformation\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t25\n\tInformant\x12(\n\x07getInfo\x12\r.TokenRequest\x1a\x0c.Information\"\x00\x62\x06proto3')



_TOKENREQUEST = DESCRIPTOR.message_types_by_name['TokenRequest']
_INFORMATION = DESCRIPTOR.message_types_by_name['Information']
TokenRequest = _reflection.GeneratedProtocolMessageType('TokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENREQUEST,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:TokenRequest)
  })
_sym_db.RegisterMessage(TokenRequest)

Information = _reflection.GeneratedProtocolMessageType('Information', (_message.Message,), {
  'DESCRIPTOR' : _INFORMATION,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:Information)
  })
_sym_db.RegisterMessage(Information)

_INFORMANT = DESCRIPTOR.services_by_name['Informant']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKENREQUEST._serialized_start=14
  _TOKENREQUEST._serialized_end=43
  _INFORMATION._serialized_start=45
  _INFORMATION._serialized_end=122
  _INFORMANT._serialized_start=124
  _INFORMANT._serialized_end=177
# @@protoc_insertion_point(module_scope)
